#pragma config(Motor,  port2,           leftBack,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           rightBack,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           rightFront,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           weaponXaxis,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           weaponYaxis,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           launch,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void driveYaxis(int speed){
	// to move forward
	motor[leftBack] = speed;
	motor[rightBack] = speed;
	motor[leftFront] = speed;
	motor[rightFront] = speed;
}

void driveTurnRight(int rspeed){
	// btn 6u to turn right
	motor[leftBack] = 127; //assign motors to channels
	motor[leftFront] = 127;
	motor[rightBack] = -1 * 127;
	motor[rightFront] = -1 * 127;
}

void driveTurnLeft(int lspeed){
	// btn 5u to turn left
	motor[leftBack] = -127; //assign motors to channels
	motor[leftFront] = -127;
	motor[rightBack] = 127;
	motor[rightFront] = 127;
}

void launch(int move){
	if(move == 1)
	{
		motor[launch] = 42;
	}
	else
	{
		motor[launch] = 0;
	}
}
